### ISSUE TITLE
problem in py execution

### ISSUE THREAD

**Issue by TheMasterRoot** [hrastnik/face_detect_n_track_py#1]
hello im trying to use your script for learning ourposes and im getting this error

```
root@jasar-VirtualBox:~/opencv-3.4.1/samples/python# python example.py
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    x, y, w, h = [int(i) for i in vfd.face()]
  File "/root/opencv-3.4.1/samples/python/video_face_detector.py", line 58, in face
    x, y, w, h = self._trackedFace
TypeError: 'NoneType' object is not iterable
```

could you help me to fix it please?

**Comment by gandharvm** [comment]
change line 14 of the script to:
`    if vfd.isFaceFound():`
The brackets were not there initially.
Changing this fixed the error for me.

**Comment by TheMasterRoot** [comment]
thank you
